version: "3.8"

services:
  repo-copilot:
    image: zenawang/repo-copilot:agents
    container_name: repo-copilot
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env