version: "3.8"

services:
  repo-copilot:
    image: zenawang/repo-copilot:doc_gen
    container_name: repo-copilot
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env