
name: Start Actions on Commit for Updating Documentation
on:
  push:
      branches:
        - '**'
  
jobs:          
  documentation:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: GPT
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
         python-version: '3.10'

      - name: Set up .env file
        run: |
          echo "GLOBAL_LLM_SERVICE=${GLOBAL_LLM_SERVICE}" >> .env
          echo "CHAT_DEPLOYMENT_NAME=${CHAT_DEPLOYMENT_NAME}" >> .env
          echo "AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}" >> .env
          echo "AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}" >> .env
          echo "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}" >> .env
          echo "AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}" >> .env
          echo "AZURE_AI_SEARCH_KEY=${AZURE_AI_SEARCH_KEY}" >> .env
          echo "API_TYPE=${API_TYPE}" >> .env
          echo "BASE_URL=${BASE_URL}" >> .env
          echo "SEARCH_ENDPOINT=${SEARCH_ENDPOINT}" >> .env
          echo "GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}" >> .env
        shell: bash
        env:
          GLOBAL_LLM_SERVICE: ${{ secrets.GLOBAL_LLM_SERVICE }}
          CHAT_DEPLOYMENT_NAME: ${{ secrets.CHAT_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_AI_SEARCH_KEY: ${{ secrets.AZURE_AI_SEARCH_KEY }}
          API_TYPE: ${{ secrets.API_TYPE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SEARCH_ENDPOINT: ${{ secrets.SEARCH_ENDPOINT }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Get local main branch
        run: |
          git fetch origin main && git checkout main
          git checkout ${{ github.ref_name }}

      - name: Run Docker Compose
        run: docker-compose up --build --detach
        env: 
          name: gpt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set safe.directory in repo-copilot container
        run: docker exec repo-copilot git config --global --add safe.directory /workspace

      - name: Run update documentation script
        run: |
          docker exec repo-copilot python3 /repo-copilot/repo_documentation/update_app.py --branch "${{ github.ref_name }}"

      - name: Commit and push if changes in repository
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Documentation Updated" && git pull --rebase)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
